apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 2
  selector:
    matchLables:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: backend
        image: test-backend:latest
        ports:
        - containersPort: 3000
        env:
        - name: HOSTNAME
          valueFrom:
            filedRef:
              filedPath: metadata.name

---
#backend service
apiVersion: v1
metadata:
  name: demo-backend
spec: 
  selector: 
    app: demo-backend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
